version: '3.9'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /mongodb-data:/data/db
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo